spring:
   boot:
    admin:
     client:
       url: https://localhost:1111/
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  
  server:
   port: 8081
      
